apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['10.43.17.248:9100']
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n\nscrape_configs:\n  - job_name: 'node-exporter'\n    static_configs:\n      - targets: ['10.43.17.248:9100']\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"prometheus"},"name":"prometheus-server-conf","namespace":"default"}}
  creationTimestamp: "2024-02-26T22:47:12Z"
  labels:
    app: prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:prometheus.yml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-02-26T22:47:12Z"
  name: prometheus-server-conf
  namespace: default
  resourceVersion: "1810"
  uid: 38026d4b-dbbf-4574-b4d5-0778765cda59
