apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9100","prometheus.io/scrape":"true"},"name":"node-exporter","namespace":"default"},"spec":{"ports":[{"name":"node-exporter","port":9100,"protocol":"TCP","targetPort":9100}],"selector":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"node-exporter"}}}
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-02-26T22:12:40Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:prometheus.io/port: {}
          f:prometheus.io/scrape: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9100,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-02-26T22:12:40Z"
  name: node-exporter
  namespace: default
  resourceVersion: "1096"
  uid: 4bd863fc-bc78-480a-ba96-abb93a94c810
spec:
  clusterIP: 10.43.17.248
  clusterIPs:
  - 10.43.17.248
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
